<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="wheel" params="prefix x y z">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

    <!-- Instantiate wheels -->
  <xacro:wheel prefix="left_front" x="${((chassis_length/2)-(0.02+wheel_radius))}" y="${-((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>
  <xacro:wheel prefix="right_front" x="${((chassis_length/2)-(0.02+wheel_radius))}" y="${((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>

  <xacro:wheel prefix="left_middle" x="0" y="${-((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>
  <xacro:wheel prefix="right_middle" x="0" y="${((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>

  <xacro:wheel prefix="left_back" x="${-((chassis_length/2)-(0.02+wheel_radius))}" y="${-((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>
  <xacro:wheel prefix="right_back" x="${-((chassis_length/2)-(0.02+wheel_radius))}" y="${((chassis_width / 2)+(wheel_length/2))}" z="${wheel_radius}"/>

</robot>