<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Links -->
  <!-- Camera base -->
  <link name="gripper_base_link">
    <visual>
      <geometry>
        <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_heigth}"/>
      </geometry>
    </visual>
  </link>
  <!-- Camera finger -->
  

<!-- Joints -->
  <!-- Gripper base to arm -->
  <joint name="arm_base_to_arm_bearing_joint" type="fixed">
    <parent link="arm_short_link"/>
    <child link="gripper_base_link"/>
    <origin xyz="${arm_short_length+(gripper_base_length/2)} ${0.01} ${(gripper_base_heigth/2)}" rpy="0 0 0"/>
    <!-- <axis xyz="0 0 1"/> -->
  </joint>

  <xacro:macro name="finger" params="prefix x y z direction">
    <link name="${prefix}_finger_link">
      <visual>
        <geometry>
          <box size="${gripper_finger_length} ${gripper_finger_width} ${gripper_finger_heigth}"/>
        </geometry>
      </visual>
    </link>
    <joint name="${prefix}_wheel_joint" type="prismatic">
      <parent link="gripper_base_link"/>
      <child link="${prefix}_finger_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <limit lower="0" upper="${gripper_finger_range}" effort="10.0" velocity="1.0"/>
      <axis xyz="0 ${direction} 0"/>
    </joint>
  </xacro:macro>

  <xacro:finger prefix="left" x="${}" y="${}" z="${}" direction="-1"/>
  <xacro:finger prefix="right" x="${}" y="${}" z="${}" direction="1"/>
</robot>